import type { Metadata } from 'next'
import { Instrument_Sans } from 'next/font/google'
import '../globals.css'
import Navbar from "@/components/Navbar";

const instrumentSans = Instrument_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Devlinks',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={instrumentSans.className + 'relative'}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
