import type { Metadata } from 'next'
import '../globals.css'
import Navbar from "@/components/Navbar";
import { LinkProvider } from '@/lib/LinksContext';

export const metadata: Metadata = {
  title: 'Devlinks',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <LinkProvider>
        <Navbar />
        {children}
    </LinkProvider>
  )
}
