import type { Metadata } from 'next'
import { Instrument_Sans } from 'next/font/google'
import './globals.css'
import Navbar from "@/components/Navbar";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/SessionProvider";

const instrumentSans = Instrument_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Devlinks',
    description: 'Generated by create next app',
}

export default async function RootLayout({children}: {
    children: React.ReactNode
}) {

    const session = await getServerSession();
    return (
        <html lang="fr">
            <body className={instrumentSans.className + 'relative'}>
                <SessionProvider session={session}>
                    {children}
                </SessionProvider>
            </body>
        </html>
    )
}
